### PR TITLE
Payment Page Functionality 

### PR DESCRIPTION
**Pull request by Annabel1054**
@AaditDubey: created the UI of the Payment Page. 

Annabel: connected the Payment Page to the Main Hotel Search Page. 
Upon filling out payment info, we will save user / reservation data into /payment and /reservation! 
Fixed the search bar bug, now everything should be working smoothly! 

Searching for random room on the specified date: 
image

Upon pressing reserve for a random room, user will be directed to Payments Page. Payments Page should include the price of the room multiplied by the number of nights.
image
image

### CODE REVIEW

**Comment by khainl1110** [comment]
image
MyBooking page frequently crashed whenever I chose it, please have a look. Thanks

**Comment by khainl1110** [comment]
image
These are the errors in MyBookings page

**Comment by jeongseungoh** [comment]
I pushed the modified mybooking page.

**Comment by khainl1110** [comment]
image
The console printed 'Successful payed' but I don't see it in my bookings tab

**Comment by khainl1110** [comment]
image
MyBookings successfully get the data but cannot display it

**Comment by khainl1110** [comment]
image
Please fix this in the code as well, pulling all the rooms (more than 500) is inefficient because the rooms data now takes up lots of data

**Pull request merged**
